CREATE TABLE IF NOT EXISTS seeds (
    id INT AUTO_INCREMENT PRIMARY KEY,
    crop_name VARCHAR(100) NOT NULL,   
    description TEXT,
    price DECIMAL(10,2) NOT NULL,            
    stock INT DEFAULT 0,                     
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
